version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  bitcoin_fetcher:
    build: 
      context: ./BitcoinFetcher
      dockerfile: Dockerfile
    container_name: bitcoin_fetcher
    depends_on:
      - redis
    environment:
      - REDIS_HOST=my-redis # Tên container của Redis
    networks:
      - app-network



networks:
  app-network:
    driver: bridge
